### ISSUE TITLE
Create T&C Modal dialog

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/auction#21]
Create a terms and condition modal that the user has to accept before he can see the auction address. This is only about creating the modal dialog and needs to be hooked in with 
https://github.com/trustlines-protocol/auction/issues/20

It should only be possible to accept after you scrolled through the hole text. 

The text is not ready, so just include some latin. 
https://baconipsum.com/?paras=8&type=all-meat&start-with-lorem=1&make-it-spicy=1

Use https://bulma.io/documentation/components/modal/

**Comment by weilbith** [comment]
There is an already full functional implementation at [his fork](https://github.com/weilbith/trustlines-foundation-website/tree/feature/auction-terms-and-conditions-modal). It is still unclear how the Bulma with Sass should be integrated. The former version uses a static compilation with the default colorscheme.
This implementation behaves exactly the same as for the merkle-drop. Only the "frameworks" for the JavaScript part differs.

**Comment by weilbith** [comment]
Okay, I want to clear this question. Let me summarize this up.
- We want to use _Bulma.io_ to style components which should be introduced for the T&C modal
- _Bulma.io_ uses `.sass` for stylesheet, where we have no support for in our current setup
- There are plans to rewrite the webpage in favor of using the _ReactJS_ framework, which would come with a bundler supporting _Sass_ per default

So for me it looks like integrating _Bulma_ requires only a temporally support for _Sass_ until a mature web bundler becomes integrated. Thereby I think it is not worth the work to integrate a _Sass_ transcompiler until then. My currently used solution approach is to stick with pure `.css` stylesheets. Therefore I used a local toolchain to transcompile the main `bulma.sass` and stored the output into the existing `css` folder.
The downside of this temporally solution is a static styling. It has been compiled without adjusting any theme colors. Doing so requires to recompile it locally again and replace the file. Furthermore this is a huge 6k of lines long file which is part of the sources in the repository. In future this gets resolved by using it as a dependency and don't checking in compiled sources.

@berndbohmeier @jondoe1337 your thoughts?

**Comment by berndbohmeier** [comment]
Lets discuss this on Monday with Max and Sascha

**Comment by berndbohmeier** [comment]
We have the transpiler setup already because of the merkle drop page, so no need to commit the 6k file for development.

**Comment by weilbith** [comment]
Implementation has been integrated into the new setup with PR trustlines-network/trustlines-foundation-website#80
